
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

const translations = {
  zh: {
    appTitle: "Project Tracker",
    dashboard: "仪表盘",
    calendar: "日历",
    settings: "全局配置",
    globalBoard: "全局看板",
    globalBoardDesc: "追踪所有活跃项目的进度与里程碑。",
    activeProjects: "活跃项目",
    completedProjects: "已完成项目",
    overallCompletion: "整体完成度",
    tasksRemaining: "剩余任务",
    totalTasks: "总任务",
    todo: "暂停",
    inProgress: "进行中",
    done: "完成",
    noTasks: "暂无任务",
    noActiveTasks: "暂无进行中任务",
    noCompletedTasks: "暂无已完成任务",
    projectProgress: "项目列表",
    left: "剩余",
    allMilestonesDone: "里程碑已全部完成",
    backToDashboard: "返回仪表盘",
    projectMilestones: "项目里程碑",
    currentFocus: "当前重点",
    nextMilestone: "下一个里程碑",
    projectTasks: "项目任务",
    allPriorities: "所有优先级",
    allStatuses: "所有状态",
    allTags: "所有标签",
    high: "高",
    medium: "中",
    low: "低",
    addTask: "添加任务",
    clearFilters: "清除筛选",
    noTasksFilter: "没有匹配的任务。",
    createFirstTask: "创建第一个任务",
    cancel: "取消",
    delete: "删除",
    saveTask: "保存任务",
    taskTitle: "任务标题",
    status: "状态",
    priority: "优先级",
    startDate: "开始日期",
    dueDate: "截止日期",
    assignee: "负责人",
    requester: "需求人",
    tags: "标签",
    addTagPlaceholder: "输入标签并回车",
    description: "描述",
    subtasks: "子任务",
    addSubtask: "添加子任务",
    addImage: "添加图片",
    remove: "移除",
    notifications: "通知",
    noNotifications: "暂无新通知",
    close: "关闭",
    month: "月",
    week: "周",
    unknownProject: "未知项目",
    subtasksCount: "子任务",
    sortByDate: "按日期排序",
    sortByPriority: "按优先级排序",
    deleteConfirm: "确定要删除吗？此操作无法撤销。",
    image: "图片",
    enterTitle: "请输入标题",
    assigneePlaceholder: "输入姓名或从配置中选择...",
    requesterPlaceholder: "输入需求方或从配置中选择...",
    descPlaceholder: "描述任务详情...",
    subtaskPlaceholder: "添加新子任务...",
    dependencies: "前置依赖任务",
    selectDependency: "选择前置任务...",
    ganttView: "甘特图",
    listView: "列表视图",
    editProject: "修改详情",
    dependencyNotice: "注意：修改此任务可能会因依赖关系自动推迟后续任务。",
    newProject: "新建项目",
    manageProjects: "管理项目", 
    createProject: "创建项目",
    projectName: "项目名称",
    projectDesc: "项目描述",
    deleteProject: "删除",
    exportData: "手动导出数据 (JSON)",
    importData: "导入数据 (JSON)",
    dataSaved: "数据已保存",
    dataImported: "数据导入成功！",
    importError: "导入失败：文件格式错误或无效。",
    confirmDeleteProject: "确定要删除整个项目及其所有任务吗？",
    searchProjects: "搜索项目...",
    // Milestone translations
    addMilestone: "添加里程碑",
    editMilestone: "编辑里程碑",
    saveMilestone: "保存里程碑",
    milestoneTitle: "里程碑标题",
    milestoneDate: "里程碑日期",
    createMilestone: "创建里程碑",
    deleteMilestoneConfirm: "确定要删除此里程碑吗？",
    confirmMilestoneUpdate: "确认里程碑状态变更",
    confirmComplete: "确定将此里程碑标记为完成吗？",
    confirmUncomplete: "确定将此里程碑标记为未完成吗？",
    confirmEarlyComplete: "提前完成！计划日期：{plan}，实际日期：{actual}。确认更新吗？",
    yesUpdate: "确认更新",
    noCancel: "取消",
    // Task Type translations
    taskType: "任务类型",
    typeNormal: "普通任务",
    typeDependent: "依赖任务",
    predecessorTask: "前置任务",
    autoCalculated: "自动计算 (基于前置任务)",
    selectPredecessorPlaceholder: "请选择前置任务...",
    // Settings
    settingsDesc: "配置常用的标签、人员、选项以及备份。",
    commonTags: "常用标签",
    commonAssignees: "常用负责人",
    commonRequesters: "常用需求方",
    addItem: "添加",
    itemPlaceholder: "输入名称...",
    saveSettings: "保存配置",
    // Project Management
    projectManagement: "项目管理中心",
    suspendProject: "挂起 (暂停)",
    terminateProject: "终止 (移入回收站)",
    restoreProject: "恢复项目",
    markCompleted: "标记完成",
    markActive: "标记活跃",
    confirmSuspend: "挂起？",
    confirmTerminate: "终止？",
    recycleBinMsg: "已移入回收站。",
    statusActive: "活跃",
    statusSuspended: "已挂起",
    statusCompleted: "已完成",
    statusTrashed: "回收站",
    actions: "操作",
    // Recycle Bin
    recycleBin: "回收站",
    recycleBinDesc: "以下是已终止的项目。您可以恢复它们或永久删除。",
    emptyRecycleBin: "回收站为空",
    deletePermanently: "永久删除",
    confirmPermanentDelete: "永久删除？不可恢复！",
    restoredMsg: "项目已恢复",
    // Backup
    dataBackup: "备份与恢复",
    autoBackup: "自动备份",
    selectBackupFolder: "选择备份文件夹（自动）",
    backupFolderSelected: "自动备份已激活",
    autoBackupDesc: "启用自动备份后，系统每小时会将数据保存到指定文件夹。手动导入导出功能随时可用。",
    enableAutoBackup: "启用每小时自动备份",
    setupBackupFirst: "请先选择一个本地文件夹用于存储备份文件。",
    backupSuccess: "自动备份成功",
    backupFailed: "自动备份失败",
    iframeError: "安全策略拦截：无法在预览窗口中访问文件夹。请点击右上角‘在新标签页打开’以使用自动备份功能。",
    // Profile
    userProfile: "个人信息",
    userName: "昵称",
    editProfile: "修改昵称",
    signOut: "退出登录 (模拟)",
    // New Dashboard Stats
    taskStatsFormat: "任务(完成/总共)",
    completionRate: "完成度",
    // New Project actions
    copyProject: "复制项目 (克隆)",
    copySuffix: " - 副本",
    // View Modes
    comfortableView: "标准模式",
    compactView: "紧凑模式"
  },
  en: {
    appTitle: "Project Tracker",
    dashboard: "Dashboard",
    calendar: "Calendar",
    settings: "Settings",
    globalBoard: "Global Board",
    globalBoardDesc: "Track progress across all your active projects.",
    activeProjects: "Active Projects",
    completedProjects: "Completed Projects",
    overallCompletion: "Overall Completion",
    tasksRemaining: "Tasks Remaining",
    totalTasks: "Total Tasks",
    todo: "Pending",
    inProgress: "Ongoing",
    done: "Done",
    noTasks: "No tasks to do.",
    noActiveTasks: "No active tasks.",
    noCompletedTasks: "No completed tasks yet.",
    projectProgress: "Project List",
    left: "left",
    allMilestonesDone: "All Milestones Done",
    backToDashboard: "Back to Dashboard",
    projectMilestones: "Project Milestones",
    currentFocus: "Current Focus",
    nextMilestone: "Next Milestone",
    projectTasks: "Project Tasks",
    allPriorities: "All Priorities",
    allStatuses: "All Statuses",
    allTags: "All Tags",
    high: "High",
    medium: "Medium",
    low: "Low",
    addTask: "Add Task",
    clearFilters: "Clear Filters",
    noTasksFilter: "No tasks match your filters.",
    createFirstTask: "Create your first task",
    cancel: "Cancel",
    delete: "Delete",
    saveTask: "Save Task",
    taskTitle: "Task Title",
    status: "Status",
    priority: "Priority",
    startDate: "Start Date",
    dueDate: "Due Date",
    assignee: "Assignee",
    requester: "Requester",
    tags: "Tags",
    addTagPlaceholder: "Add tag and press Enter",
    description: "Description",
    subtasks: "Subtasks",
    addSubtask: "Add subtask",
    addImage: "Add Image",
    remove: "Remove",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    close: "Close",
    month: "Month",
    week: "Week",
    unknownProject: "Unknown Project",
    subtasksCount: "subtasks",
    sortByDate: "Sort by Date",
    sortByPriority: "Sort by Priority",
    deleteConfirm: "Are you sure? This cannot be undone.",
    image: "Image",
    enterTitle: "Enter title",
    assigneePlaceholder: "Name or select from settings...",
    requesterPlaceholder: "Requester or select from settings...",
    descPlaceholder: "Describe the task details...",
    subtaskPlaceholder: "Add a new subtask...",
    dependencies: "Dependencies",
    selectDependency: "Select dependency...",
    ganttView: "Gantt Chart",
    listView: "List View",
    editProject: "Edit Details",
    dependencyNotice: "Note: Modifying this task may auto-shift dependent tasks.",
    newProject: "New Project",
    manageProjects: "Manage Projects", 
    createProject: "Create Project",
    projectName: "Project Name",
    projectDesc: "Project Description",
    deleteProject: "Delete",
    exportData: "Manual Export (JSON)",
    importData: "Import Data (JSON)",
    dataSaved: "Data Saved",
    dataImported: "Data imported successfully!",
    importError: "Import failed: Invalid file format.",
    confirmDeleteProject: "Are you sure you want to delete this project and all its tasks?",
    searchProjects: "Search projects...",
    // Milestone translations
    addMilestone: "Add Milestone",
    editMilestone: "Edit Milestone",
    saveMilestone: "Save Milestone",
    milestoneTitle: "Milestone Title",
    milestoneDate: "Milestone Date",
    createMilestone: "Create Milestone",
    deleteMilestoneConfirm: "Are you sure you want to delete this milestone?",
    confirmMilestoneUpdate: "Confirm Milestone Update",
    confirmComplete: "Are you sure you want to mark this milestone as completed?",
    confirmUncomplete: "Are you sure you want to mark this milestone as incomplete?",
    confirmEarlyComplete: "Completed ahead of schedule! Plan: {plan}, Actual: {actual}. Confirm update?",
    yesUpdate: "Yes, Update",
    noCancel: "Cancel",
    // Task Type translations
    taskType: "Task Type",
    typeNormal: "Normal Task",
    typeDependent: "Dependent Task",
    predecessorTask: "Predecessor Task",
    autoCalculated: "Auto-calculated (based on predecessor)",
    selectPredecessorPlaceholder: "Select predecessor task...",
    // Settings
    settingsDesc: "Configure common tags, people, options and backups.",
    commonTags: "Common Tags",
    commonAssignees: "Common Assignees",
    commonRequesters: "Common Requesters",
    addItem: "Add",
    itemPlaceholder: "Enter name...",
    saveSettings: "Save Settings",
    // Project Management
    projectManagement: "Project Management Center",
    suspendProject: "Suspend (Pause)",
    terminateProject: "Terminate (To Trash)",
    restoreProject: "Restore",
    markCompleted: "Mark Completed",
    markActive: "Mark Active",
    confirmSuspend: "Suspend?",
    confirmTerminate: "Terminate?",
    recycleBinMsg: "Project moved to recycle bin.",
    statusActive: "Active",
    statusSuspended: "Suspended",
    statusCompleted: "Completed",
    statusTrashed: "Trash",
    actions: "Actions",
    // Recycle Bin
    recycleBin: "Recycle Bin",
    recycleBinDesc: "The following items have been terminated. You can restore them or delete them permanently.",
    emptyRecycleBin: "Recycle Bin is empty",
    deletePermanently: "Delete Forever",
    confirmPermanentDelete: "Delete Forever?",
    restoredMsg: "Project restored",
    // Backup
    dataBackup: "Backup & Restore",
    autoBackup: "Auto Backup",
    selectBackupFolder: "Select Backup Folder (Auto)",
    backupFolderSelected: "Auto Backup Active",
    autoBackupDesc: "When enabled, the system will auto-save data to your local folder every hour. Manual Import/Export is always available.",
    enableAutoBackup: "Enable Hourly Auto Backup",
    setupBackupFirst: "Please select a local folder for storing backups first.",
    backupSuccess: "Auto backup successful",
    backupFailed: "Auto backup failed",
    iframeError: "Security Block: Folder access is not allowed in preview mode. Click 'Open in New Tab' to use Auto Backup.",
    // Profile
    userProfile: "User Profile",
    userName: "Display Name",
    editProfile: "Edit Name",
    signOut: "Sign Out (Mock)",
    // New Dashboard Stats
    taskStatsFormat: "Tasks (Done/Total)",
    completionRate: "Completion",
    // New Project actions
    copyProject: "Copy (Clone)",
    copySuffix: " - Copy",
    // View Modes
    comfortableView: "Comfortable View",
    compactView: "Compact View"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations['zh'];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const value = {
    language,
    setLanguage,
    t: translations[language]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
